FROM balenalib/raspberry-pi-python:3.7-build

WORKDIR /app

COPY audio/sounds /music
COPY audio/music /music
COPY src/conductor/ .

RUN [ "cross-build-start" ]
RUN install_packages libatlas-base-dev python3-numpy ffmpeg omxplayer
RUN pip3 install --upgrade pip
RUN pip3 install -r requirements.txt

RUN ffmpeg-normalize -vf /music/*.mp3
RUN [ "cross-build-end" ]


CMD python conductor.py