FROM  balenalib/rpi-raspbian:latest

ENV UDEV=1


WORKDIR /app
#COPY . .
COPY pkg pkg
COPY go.mod go.mod
COPY go.sum go.sum
COPY src/music_vault .


RUN [ "cross-build-start" ]
RUN install_packages \
    build-essential \
    git \
    wget \
    golang

RUN go mod tidy
RUN go mod download
#RUN go test
RUN go build 

RUN [ "cross-build-end" ]

#COPY ./music /music


CMD ./music_vault