FROM  balenalib/rpi-raspbian:latest

ENV UDEV=1

WORKDIR /app
COPY . .

#COPY pkg .
#COPY vendor .
#COPY go.mod .
#COPY go.sum .
#COPY src/conductor .


RUN [ "cross-build-start" ]
RUN install_packages \
    build-essential \
    git \
    wget \
    golang \
    omxplayer

RUN go mod tidy
RUN go mod download
#RUN go test
RUN go build ./src/conductor

RUN [ "cross-build-end" ]

CMD ./conductor